client: fix vulnerabilities found in  `npm audit`
coreos/fcct-online pull request #17
Opened 2020-03-16 18:38 UTC by zonggen

Fixed previous vulnerabilities returned by `npm audit`, after the fix:

```
$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 25779 scanned packages
```

Closes: https://issues.redhat.com/browse/GRPA-1795
Signed-off-by: Allen Bai <abai@redhat.com>

2020-03-16 18:41 UTC, zonggen commented
Fixed by running `npm audit --fix`, manually `npm install --save-dev` and `npm install core-js@3`.

2020-03-16 19:45 UTC, ashcrow requested changes
`minimist` needs updating.

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
> +            "serialize-javascript": "^2.1.2",
:+1:

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
> +        "serialize-javascript": "^2.1.2",
:+1:

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
> +      "version": "2.1.2",
:+1:

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
> +        "serialize-javascript": "^2.1.2",
:+1:

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
> +          "version": "6.4.1",
:+1:

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
> +          "version": "6.4.1",
:+1:

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
> +        "acorn": "^6.2.1",
:+1:

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
> +        "acorn": "^7.1.1",
:+1:

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
> +          "version": "7.1.1",
:+1:

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
> +        "acorn": "^7.1.0",
:+1:

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
> +        "acorn": {
:+1:

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
>          "minimist": "^1.2.0"
:-1:

2020-03-16 19:45 UTC, ashcrow commented on client/package-lock.json
> +        "minimist": "^1.2.0",
:-1:  1.2.2+

2020-03-16 20:30 UTC, zonggen commented
Bumped minimist to 1.2.2, though not sure why the `npm audit` wouldn't show `minimist 1.2.0` as a vulnerability. And `npm install --save minimist@1.2.2` is not updating all of the minimist version. Not sure if we need all of the version to be 1.2.2.

2020-03-16 20:30 UTC, zonggen commented
```diff
diff --git a/client/package-lock.json b/client/package-lock.json
index 083f06f..379a885 100644
--- a/client/package-lock.json
+++ b/client/package-lock.json
@@ -9573,9 +9573,9 @@
       }
     },
     "minimist": {
-      "version": "1.2.0",
-      "resolved": "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz",
-      "integrity": "sha1-o1AIsg9BOD7sH7kU9M1d95omQoQ=",
+      "version": "1.2.2",
+      "resolved": "https://registry.npmjs.org/minimist/-/minimist-1.2.2.tgz",
+      "integrity": "sha512-rIqbOrKb8GJmx/5bc2M0QchhUouMXSpd1RTclXsB41JdL+VtnojfaJR+h7F9k18/4kHUsBFgk80Uk+q569vjPA==",
       "dev": true
     },
     "minipass": {

```

2020-03-16 20:32 UTC, zonggen commented
```
$ npm list minimist

client@0.1.0 /home/abai/git/fcct-online/client
├─┬ @vue/cli-plugin-babel@4.2.3
│ ├─┬ @babel/core@7.8.7
│ │ └─┬ json5@2.1.1
│ │   └── minimist@1.2.2  deduped
│ └─┬ babel-loader@8.0.6
│   └─┬ loader-utils@1.2.3
│     └─┬ json5@1.0.1
│       └── minimist@1.2.2  deduped
├─┬ @vue/cli-service@4.2.3
│ ├── minimist@1.2.2 
│ └─┬ webpack-dev-server@3.10.3
│   └─┬ chokidar@2.1.8
│     └─┬ UNMET OPTIONAL DEPENDENCY fsevents@1.2.9
│       └─┬ UNMET OPTIONAL DEPENDENCY node-pre-gyp@0.12.0
│         ├─┬ UNMET OPTIONAL DEPENDENCY mkdirp@0.5.1
│         │ └── UNMET OPTIONAL DEPENDENCY minimist@0.0.8 
│         └─┬ UNMET OPTIONAL DEPENDENCY rc@1.2.8
│           └── UNMET OPTIONAL DEPENDENCY minimist@1.2.0 
└─┬ eslint@5.16.0
  └─┬ mkdirp@0.5.1
    └── minimist@0.0.8 
```

2020-03-16 20:46 UTC, ashcrow commented
All but this one looks good to me:

```
└─┬ eslint@5.16.0
  └─┬ mkdirp@0.5.1
    └── minimist@0.0.8 
```
0.0.8 sounds very old! :fearful:

2020-03-16 21:39 UTC, zonggen commented
I don't think I can manually bump version for dependencies used by eslint.. 
Tried to force bump to 1.2.2:
```
└─┬ eslint@5.16.0
  └─┬ mkdirp@0.5.1
    └── minimist@1.2.2  invalid
``` 
And the latest eslint version 6.8.0 is still using minimist 0.0.8:
```
└─┬ eslint@6.8.0
  └─┬ mkdirp@0.5.1
    └── minimist@0.0.8 
```

I think it'd be best to check which minimist is creating the security vulnerability and fix that specific dependency version directly.

2020-03-17 16:07 UTC, ashcrow approved these changes

2020-03-17 16:07 UTC, ashcrow commented
Do we need `eslint`?

2020-03-17 19:04 UTC, zonggen commented
Investigated a little, seems like the `@vue/cli-plugin-babel@4.2.3` use `mkdirp@0.5.1` as part of the dependencies, and removing `eslint` would cause vue not functioning.

2020-03-17 20:42 UTC, ashcrow commented
This gets us further along. I think it's good to go. :+1:

2020-03-17 21:10 UTC, zonggen commented
Thank you for reviewing :smiley: 

Merging >>>

2020-03-17 21:11 UTC, merged